title: "Manuel A. Sánchez"
subtitle: "Personal Academic Webpage"
email: "manuel.sanchez@ing.puc.cl"

description: "Associate Professor | Institute for Mathematical and Computational Engineering (IMC), UC Chile"
author: "Manuel A. Sánchez"
github_username: "ManuelSanchezUribe"

use_logo: true
logo: MASUcircle.png

include:
  - assets
  - old_page

exclude:
  - .ipynb_checkpoints
