theme: jekyll-theme-slate

github:
  is_project_page: false
  
title: "Manuel A. Sanchez"
subtitle: "personal webpage"
email: "manuel.sanchez@ing.puc.cl"

description: "Assistant Professor <br> Institute for Mathematical and Computational Enginnering"
author: "Manuel"
github_username: "ManuelSanchezUribe"
credits: None

author_bio: Hi, my name is John Doe. I built this site using devlopr-jekyll :D
