theme: jekyll-theme-slate

github:
  is_project_page: false
  
title: "Manuel A. Sánchez"
subtitle: "personal webpage"
email: "manuel.sanchez@ing.puc.cl"

description: "Assistant Professor <br> Institute for Mathematical and Computational Engineering <br> UC Chile"
author: "Manuel"
github_username: "ManuelSanchezUribe"

use_logo: true

# logo image to use. logo images are constrained at 50px in height.
logo: MASUcircle.png
