theme: jekyll-theme-midnight

github:
  is_project_page: false
  
title: "Manuel A. Sanchez"
subtitle: " "
email: "manuel.sanchez@ing.puc.cl"

description: "Assistant Professor \n IMC"
author: "Manuel"
github_username: "ManuelSanchezUribe"
credits: None

author_bio: Hi, my name is John Doe. I built this site using devlopr-jekyll :D
