theme: jekyll-theme-slate

github:
  is_project_page: false
  
title: "Manuel A. Sánchez"
subtitle: "personal webpage"
email: "manuel.sanchez@ing.puc.cl"

description: "Assistant Professor <br> Institute for Mathematical and Computational Engineering UC"
author: "Manuel"
github_username: "ManuelSanchezUribe"
logo: MASUcircle.png
