theme: jekyll-theme-midnight

title: "Manuel A. Sanchez"
email: "manuel.sanchez@ing.puc.cl"

description: "personal website"
author: "Manuel"
github_username: "ManuelSanchezUribe"

author_bio: Hi, my name is John Doe. I built this site using devlopr-jekyll :D
